services:
  migrations:
    image: ghcr.io/aikenahac/echo:master
    container_name: echo-migrations
    env_file:
      - .env
    depends_on:
      db:
        condition: service_healthy
    command: sh -c "node dist/migrate.js && exit 0"
    restart: "no"
    networks:
      - echo-network

  app:
    image: ghcr.io/aikenahac/echo:master
    container_name: echo
    env_file:
      - .env
    ports:
      - "3104:3000"
    depends_on:
      db:
        condition: service_healthy
      migrations:
        condition: service_completed_successfully
    restart: unless-stopped
    networks:
      - echo-network

  db:
    image: postgres:17
    container_name: echo-db
    env_file:
      - .env
    volumes:
      - echo_db_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 10s
      timeout: 5s
      retries: 5
    restart: unless-stopped
    networks:
      - echo-network

volumes:
  echo_db_data:

networks:
  echo-network:
    driver: bridge